package hook

import (
	"fmt"
	"io"
)

// Generate writes the auto-help.sh hook script to w.
// The generated script looks up help text from the static DB directory
// instead of running --help dynamically.
// When lazy is true, the script also collects help on-demand for unknown commands.
func Generate(w io.Writer, dbDir string, lazy bool) error {
	if lazy {
		_, err := fmt.Fprintf(w, lazyHookTemplate, dbDir)
		return err
	}
	_, err := fmt.Fprintf(w, hookTemplate, dbDir)
	return err
}

const hookTemplate = `#!/usr/bin/env bash
# auto-help.sh - PreToolUse hook for Bash tool
# Looks up pre-built CLI help from static database
# Generated by: cli-help-db hook

INPUT=$(cat) || exit 0

# Extract command from tool input
PARSED=$(echo "$INPUT" | jq -r '[.session_id, .tool_input.command] | @tsv') || exit 0
IFS=$'\t' read -r SESSION_ID CMD <<< "$PARSED"

[[ -z "$CMD" || "$CMD" == "null" ]] && exit 0

# Extract first command (before pipes, redirects, etc.)
FIRST_CMD=$(echo "$CMD" | sed 's/[|><;&]\{1,\}.*//' | xargs) || exit 0

read -ra TOKENS <<< "$FIRST_CMD"
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip shell variable / subshell expansion
[[ "${TOKENS[0]}" == '$'* || "${TOKENS[0]}" == '$('* || "${TOKENS[0]}" == '` + "`" + `'* ]] && exit 0

# Strip sudo / env / wrapper commands
while [[ ${#TOKENS[@]} -gt 0 ]]; do
  case "${TOKENS[0]}" in
    sudo|env|nohup|nice|strace|time) TOKENS=("${TOKENS[@]:1}") ;;
    *) break ;;
  esac
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip env VAR=val
while [[ ${#TOKENS[@]} -gt 0 && "${TOKENS[0]}" == *=* ]]; do
  TOKENS=("${TOKENS[@]:1}")
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

BASE_CMD=$(basename "${TOKENS[0]}")

# Path traversal guard
[[ "$BASE_CMD" == */* ]] && exit 0

# Skip npx/bunx (may trigger package downloads)
[[ "$BASE_CMD" == "npx" || "$BASE_CMD" == "bunx" ]] && exit 0

# Session-level dedup (avoid repeating same help in one session)
CACHE_DIR="/tmp/claude-help-cache/${SESSION_ID}"
mkdir -p "$CACHE_DIR" 2>/dev/null || exit 0
CACHE_FILE="${CACHE_DIR}/${BASE_CMD}"
[[ -f "$CACHE_FILE" ]] && exit 0

# Look up from static database
HELP_DB_DIR="%s"
HELP_FILE="${HELP_DB_DIR}/${BASE_CMD}.txt"

[[ ! -f "$HELP_FILE" ]] && exit 0

HELP_OUTPUT=$(cat "$HELP_FILE")
[[ -z "$HELP_OUTPUT" ]] && exit 0

touch "$CACHE_FILE"

jq -n --arg help "$HELP_OUTPUT" --arg cmd "$BASE_CMD" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    additionalContext: ("CLI Reference: " + $cmd + " --help\n" + $help)
  }
}'
`

const lazyHookTemplate = `#!/usr/bin/env bash
# auto-help.sh - PreToolUse hook for Bash tool
# Looks up pre-built CLI help from static database
# With lazy collection: fetches --help on-demand for unknown commands
# Generated by: cli-help-db hook --lazy

INPUT=$(cat) || exit 0

# Extract command from tool input
PARSED=$(echo "$INPUT" | jq -r '[.session_id, .tool_input.command] | @tsv') || exit 0
IFS=$'\t' read -r SESSION_ID CMD <<< "$PARSED"

[[ -z "$CMD" || "$CMD" == "null" ]] && exit 0

# Extract first command (before pipes, redirects, etc.)
FIRST_CMD=$(echo "$CMD" | sed 's/[|><;&]\{1,\}.*//' | xargs) || exit 0

read -ra TOKENS <<< "$FIRST_CMD"
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip shell variable / subshell expansion
[[ "${TOKENS[0]}" == '$'* || "${TOKENS[0]}" == '$('* || "${TOKENS[0]}" == '` + "`" + `'* ]] && exit 0

# Strip sudo / env / wrapper commands
while [[ ${#TOKENS[@]} -gt 0 ]]; do
  case "${TOKENS[0]}" in
    sudo|env|nohup|nice|strace|time) TOKENS=("${TOKENS[@]:1}") ;;
    *) break ;;
  esac
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip env VAR=val
while [[ ${#TOKENS[@]} -gt 0 && "${TOKENS[0]}" == *=* ]]; do
  TOKENS=("${TOKENS[@]:1}")
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

BASE_CMD=$(basename "${TOKENS[0]}")

# Path traversal guard
[[ "$BASE_CMD" == */* ]] && exit 0

# Skip npx/bunx (may trigger package downloads)
[[ "$BASE_CMD" == "npx" || "$BASE_CMD" == "bunx" ]] && exit 0

# Session-level dedup (avoid repeating same help in one session)
CACHE_DIR="/tmp/claude-help-cache/${SESSION_ID}"
mkdir -p "$CACHE_DIR" 2>/dev/null || exit 0
CACHE_FILE="${CACHE_DIR}/${BASE_CMD}"
[[ -f "$CACHE_FILE" ]] && exit 0

# Look up from static database
HELP_DB_DIR="%s"
HELP_FILE="${HELP_DB_DIR}/${BASE_CMD}.txt"

if [[ ! -f "$HELP_FILE" ]]; then
  # Lazy collect: try --help, then -h (skip man — too slow for hook context)
  mkdir -p "$HELP_DB_DIR" 2>/dev/null || exit 0

  # Use timeout if available, otherwise run directly
  if command -v timeout &>/dev/null; then
    HELP_OUTPUT=$(timeout 2 "$BASE_CMD" --help 2>&1) || true
    if [[ ${#HELP_OUTPUT} -lt 10 ]]; then
      HELP_OUTPUT=$(timeout 2 "$BASE_CMD" -h 2>&1) || true
    fi
  else
    HELP_OUTPUT=$("$BASE_CMD" --help 2>&1) || true
    if [[ ${#HELP_OUTPUT} -lt 10 ]]; then
      HELP_OUTPUT=$("$BASE_CMD" -h 2>&1) || true
    fi
  fi
  [[ ${#HELP_OUTPUT} -lt 10 ]] && exit 0

  # Truncate to 60 lines
  HELP_OUTPUT=$(printf '%%s' "$HELP_OUTPUT" | head -n 60)

  # Atomic write to DB
  TMP_FILE=$(mktemp "${HELP_DB_DIR}/.${BASE_CMD}.XXXXXX") || exit 0
  printf '%%s' "$HELP_OUTPUT" > "$TMP_FILE"
  mv "$TMP_FILE" "$HELP_FILE"
else
  HELP_OUTPUT=$(cat "$HELP_FILE")
fi

[[ -z "$HELP_OUTPUT" ]] && exit 0

touch "$CACHE_FILE"

jq -n --arg help "$HELP_OUTPUT" --arg cmd "$BASE_CMD" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    additionalContext: ("CLI Reference: " + $cmd + " --help\n" + $help)
  }
}'
`
