package hook

import (
	"fmt"
	"io"
)

// Generate writes the auto-help.sh hook script to w.
// The generated script looks up help text from the static DB directory
// instead of running --help dynamically.
// When lazy is true, the script also collects help on-demand for unknown commands.
func Generate(w io.Writer, dbDir string, lazy bool) error {
	if lazy {
		_, err := fmt.Fprintf(w, lazyHookTemplate, dbDir)
		return err
	}
	_, err := fmt.Fprintf(w, hookTemplate, dbDir)
	return err
}

const hookTemplate = `#!/usr/bin/env bash
# auto-help.sh - PreToolUse hook for Bash tool
# Looks up pre-built CLI help from static database (with subcommand support)
# Generated by: cli-help-db hook

INPUT=$(cat) || exit 0

# Extract command from tool input
PARSED=$(echo "$INPUT" | jq -r '[.session_id, .tool_input.command] | @tsv') || exit 0
IFS=$'\t' read -r SESSION_ID CMD <<< "$PARSED"

[[ -z "$CMD" || "$CMD" == "null" ]] && exit 0

# Extract first command (before pipes, redirects, etc.)
FIRST_CMD=$(echo "$CMD" | sed 's/[|><;&]\{1,\}.*//' | xargs) || exit 0

read -ra TOKENS <<< "$FIRST_CMD"
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip shell variable / subshell expansion
[[ "${TOKENS[0]}" == '$'* || "${TOKENS[0]}" == '$('* || "${TOKENS[0]}" == '` + "`" + `'* ]] && exit 0

# Strip sudo / env / wrapper commands
while [[ ${#TOKENS[@]} -gt 0 ]]; do
  case "${TOKENS[0]}" in
    sudo|env|nohup|nice|strace|time) TOKENS=("${TOKENS[@]:1}") ;;
    *) break ;;
  esac
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip env VAR=val
while [[ ${#TOKENS[@]} -gt 0 && "${TOKENS[0]}" == *=* ]]; do
  TOKENS=("${TOKENS[@]:1}")
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

BASE_CMD=$(basename "${TOKENS[0]}")

# Path traversal guard
[[ "$BASE_CMD" == */* ]] && exit 0

# Skip npx/bunx (may trigger package downloads)
[[ "$BASE_CMD" == "npx" || "$BASE_CMD" == "bunx" ]] && exit 0

# Build subcommand lookup key (e.g. docker__container__ls)
# Collect non-flag tokens up to depth 3
LOOKUP_KEY="$BASE_CMD"
MAX_DEPTH=3
for ((i=1; i<${#TOKENS[@]} && i<MAX_DEPTH; i++)); do
  TOKEN="${TOKENS[$i]}"
  [[ "$TOKEN" == -* ]] && break
  # Skip tokens that look like arguments (contain / or .)
  [[ "$TOKEN" == */* || "$TOKEN" == *.* ]] && break
  LOOKUP_KEY="${LOOKUP_KEY}__${TOKEN}"
done

# Session-level dedup (avoid repeating same help in one session)
CACHE_DIR="/tmp/claude-help-cache/${SESSION_ID}"
mkdir -p "$CACHE_DIR" 2>/dev/null || exit 0
CACHE_FILE="${CACHE_DIR}/${LOOKUP_KEY}"
[[ -f "$CACHE_FILE" ]] && exit 0

# Look up from static database (longest match first)
HELP_DB_DIR="%s"
HELP_OUTPUT=""
MATCHED_KEY=""
TRY_KEY="$LOOKUP_KEY"
while [[ -n "$TRY_KEY" ]]; do
  HELP_FILE="${HELP_DB_DIR}/${TRY_KEY}.txt"
  if [[ -f "$HELP_FILE" ]]; then
    HELP_OUTPUT=$(cat "$HELP_FILE")
    MATCHED_KEY="$TRY_KEY"
    break
  fi
  # Remove last __ segment (single %% via Fprintf = bash shortest suffix match)
  SHORTER="${TRY_KEY%%__*}"
  [[ "$SHORTER" == "$TRY_KEY" ]] && break  # no __ left
  TRY_KEY="$SHORTER"
done

[[ -z "$HELP_OUTPUT" ]] && exit 0

DISPLAY_CMD="${MATCHED_KEY//__/ }"
touch "$CACHE_FILE"

jq -n --arg help "$HELP_OUTPUT" --arg cmd "$DISPLAY_CMD" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    additionalContext: ("CLI Reference: " + $cmd + " --help\n" + $help)
  }
}'
`

const lazyHookTemplate = `#!/usr/bin/env bash
# auto-help.sh - PreToolUse hook for Bash tool
# Looks up pre-built CLI help from static database (with subcommand support)
# With lazy collection: fetches --help on-demand for unknown commands
# TTL-based refresh: re-collects help after 30 days
# Generated by: cli-help-db hook --lazy

INPUT=$(cat) || exit 0

# Extract command from tool input
PARSED=$(echo "$INPUT" | jq -r '[.session_id, .tool_input.command] | @tsv') || exit 0
IFS=$'\t' read -r SESSION_ID CMD <<< "$PARSED"

[[ -z "$CMD" || "$CMD" == "null" ]] && exit 0

# Extract first command (before pipes, redirects, etc.)
FIRST_CMD=$(echo "$CMD" | sed 's/[|><;&]\{1,\}.*//' | xargs) || exit 0

read -ra TOKENS <<< "$FIRST_CMD"
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip shell variable / subshell expansion
[[ "${TOKENS[0]}" == '$'* || "${TOKENS[0]}" == '$('* || "${TOKENS[0]}" == '` + "`" + `'* ]] && exit 0

# Strip sudo / env / wrapper commands
while [[ ${#TOKENS[@]} -gt 0 ]]; do
  case "${TOKENS[0]}" in
    sudo|env|nohup|nice|strace|time) TOKENS=("${TOKENS[@]:1}") ;;
    *) break ;;
  esac
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

# Skip env VAR=val
while [[ ${#TOKENS[@]} -gt 0 && "${TOKENS[0]}" == *=* ]]; do
  TOKENS=("${TOKENS[@]:1}")
done
[[ ${#TOKENS[@]} -eq 0 ]] && exit 0

BASE_CMD=$(basename "${TOKENS[0]}")

# Path traversal guard
[[ "$BASE_CMD" == */* ]] && exit 0

# Skip npx/bunx (may trigger package downloads)
[[ "$BASE_CMD" == "npx" || "$BASE_CMD" == "bunx" ]] && exit 0

# Build subcommand lookup key (e.g. docker__container__ls)
# Collect non-flag tokens up to depth 3
LOOKUP_KEY="$BASE_CMD"
MAX_DEPTH=3
for ((i=1; i<${#TOKENS[@]} && i<MAX_DEPTH; i++)); do
  TOKEN="${TOKENS[$i]}"
  [[ "$TOKEN" == -* ]] && break
  # Skip tokens that look like arguments (contain / or .)
  [[ "$TOKEN" == */* || "$TOKEN" == *.* ]] && break
  LOOKUP_KEY="${LOOKUP_KEY}__${TOKEN}"
done

# Session-level dedup (avoid repeating same help in one session)
CACHE_DIR="/tmp/claude-help-cache/${SESSION_ID}"
mkdir -p "$CACHE_DIR" 2>/dev/null || exit 0
CACHE_FILE="${CACHE_DIR}/${LOOKUP_KEY}"
[[ -f "$CACHE_FILE" ]] && exit 0

# TTL helper: check if file is older than 30 days
TTL_SECONDS=$((30 * 86400))
is_expired() {
  local file="$1"
  [[ ! -f "$file" ]] && return 0
  local now mtime age
  now=$(date +%%s)
  if stat -c %%Y /dev/null &>/dev/null 2>&1; then
    mtime=$(stat -c %%Y "$file")
  else
    mtime=$(stat -f %%m "$file")
  fi
  age=$((now - mtime))
  [[ $age -gt $TTL_SECONDS ]]
}

# Lazy collect helper: try --help, -h, then help subcommand
lazy_collect() {
  local cmd_key="$1"
  local display_cmd="${cmd_key//__/ }"
  read -ra CMD_PARTS <<< "$display_cmd"

  local help_output=""

  # Try {cmd} {sub...} --help
  if command -v timeout &>/dev/null; then
    help_output=$(timeout 2 "${CMD_PARTS[@]}" --help 2>&1) || true
  else
    help_output=$("${CMD_PARTS[@]}" --help 2>&1) || true
  fi

  # Try {cmd} {sub...} -h
  if [[ ${#help_output} -lt 10 ]]; then
    if command -v timeout &>/dev/null; then
      help_output=$(timeout 2 "${CMD_PARTS[@]}" -h 2>&1) || true
    else
      help_output=$("${CMD_PARTS[@]}" -h 2>&1) || true
    fi
  fi

  # Try {cmd} help {sub...} (for tools like docker, go)
  if [[ ${#help_output} -lt 10 && ${#CMD_PARTS[@]} -gt 1 ]]; then
    local exe="${CMD_PARTS[0]}"
    local subs=("${CMD_PARTS[@]:1}")
    if command -v timeout &>/dev/null; then
      help_output=$(timeout 2 "$exe" help "${subs[@]}" 2>&1) || true
    else
      help_output=$("$exe" help "${subs[@]}" 2>&1) || true
    fi
  fi

  [[ ${#help_output} -lt 10 ]] && return 1

  # Truncate to 60 lines and write to DB
  help_output=$(printf '%%s' "$help_output" | head -n 60)
  mkdir -p "$HELP_DB_DIR" 2>/dev/null || return 1
  local tmp_file
  tmp_file=$(mktemp "${HELP_DB_DIR}/.${cmd_key}.XXXXXX") || return 1
  printf '%%s' "$help_output" > "$tmp_file"
  mv "$tmp_file" "${HELP_DB_DIR}/${cmd_key}.txt"
  echo "$help_output"
}

# Look up from static database (longest match first, with TTL check)
HELP_DB_DIR="%s"
HELP_OUTPUT=""
MATCHED_KEY=""
NEEDS_REFRESH=false
TRY_KEY="$LOOKUP_KEY"
while [[ -n "$TRY_KEY" ]]; do
  HELP_FILE="${HELP_DB_DIR}/${TRY_KEY}.txt"
  if [[ -f "$HELP_FILE" ]]; then
    if is_expired "$HELP_FILE"; then
      NEEDS_REFRESH=true
      MATCHED_KEY="$TRY_KEY"
    else
      HELP_OUTPUT=$(cat "$HELP_FILE")
      MATCHED_KEY="$TRY_KEY"
    fi
    break
  fi
  # Remove last __ segment (single %% via Fprintf = bash shortest suffix match)
  SHORTER="${TRY_KEY%%__*}"
  [[ "$SHORTER" == "$TRY_KEY" ]] && break  # no __ left
  TRY_KEY="$SHORTER"
done

# Lazy collect: no match found, or TTL expired — try to collect
if [[ -z "$HELP_OUTPUT" ]]; then
  # Try from longest key down to base command
  TRY_KEY="$LOOKUP_KEY"
  while [[ -n "$TRY_KEY" ]]; do
    HELP_OUTPUT=$(lazy_collect "$TRY_KEY")
    if [[ -n "$HELP_OUTPUT" ]]; then
      MATCHED_KEY="$TRY_KEY"
      break
    fi
    SHORTER="${TRY_KEY%%__*}"
    [[ "$SHORTER" == "$TRY_KEY" ]] && break
    TRY_KEY="$SHORTER"
  done
fi

[[ -z "$HELP_OUTPUT" ]] && exit 0

DISPLAY_CMD="${MATCHED_KEY//__/ }"
touch "$CACHE_FILE"

jq -n --arg help "$HELP_OUTPUT" --arg cmd "$DISPLAY_CMD" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    additionalContext: ("CLI Reference: " + $cmd + " --help\n" + $help)
  }
}'
`
